
package cat.proven.realestatedomgui.views;

/**
 *
 * @author ProvenSoft
 */
public class WelcomePanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbWelcome = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 0));
        setLayout(new java.awt.BorderLayout());

        lbWelcome.setForeground(new java.awt.Color(255, 0, 51));
        lbWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWelcome.setText("Welcome to Real Estate application with XML DOM");
        add(lbWelcome, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbWelcome;
    // End of variables declaration//GEN-END:variables
}
